### ISSUE TITLE
Fix CHS theme after restore in sandbox

### ISSUE THREAD

**Issue by laddhanson** [calhist/dam_workflow_scripts#13]
The theme is there, but broken.  Doesn't seem to be a cache issue.  Does seem to be related to the views module.

Things to try:
- [ ] disable/enable views modules
- [ ] disable/enable features and related modules

**Comment by calhist** [comment]
One major symptom of the problem is that sidebars are displaying at full-width, instead of being limited to 1/3 width… they’re missing the `<section>` wrapper for some reason. See screenshot.

It's as though some of the theme files and CSS are either not loading or are different versions than in prod.

![image](https://cloud.githubusercontent.com/assets/25800148/24114735/7dab56a4-0d5e-11e7-8076-ecc7c39f028e.png)

**Comment by laddhanson** [comment]
Rather than just restore the custom chs_them changed script to sync all of sites/all/themes/.
